FROM python:3.9-slim-buster

WORKDIR /app
COPY . .

COPY requirements.txt .
# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt


RUN pip install -e ".[dev]"

CMD ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]